# Generated by Django 3.1 on 2020-08-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_reader_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
